### ISSUE TITLE
Nice work, but where are the Dockerfiles for the images

### ISSUE THREAD

**Issue by SydOps** [netsil/netsil-kube#12]
This project looks very useful. But when I try to implement, I have to stop. 

All images used in this repo are directly pulled from hub.docker.com without Dockerfile. It is hard for me to use, because we need build the images internally. 

Could you share to us, that we can maintant them as well.

**Comment by luhkevin** [comment]
Sorry, even if we gave you the Dockerfile, it would not do much good, as we are not an open-source company. 

If you wish to build an image from our existing image, you can use the `FROM` command in your Dockerfile.
